### ISSUE TITLE
Genres service implementation

### ISSUE THREAD

**Issue by FrancescObrador** [FrancescObrador/AdoptaUnJunior#1]
The `GenresService` class is defined with unimplemented methods for handling CRUD operations on book genres. We need to implement the following methods:

### **Tasks:**

1. **Create Genre:**
   - Implement the `create` method to save a new genre to the database.

2. **Find All Genres:**
   - Implement the `findAll` method to retrieve all genres from the database.

3. **Find Genre by ID:**
   - Implement the `findOne` method to retrieve a genre by its ID.

4. **Update Genre:**
   - Implement the `update(` method to update an existing genre's details.

5. **Delete Genre:**
   - Implement the `remove` method to delete a genre by its ID.
   
  ### **Additional Information**
These service methods have tests implemented in genres.service.spec.ts, and the corresponding controller tests are implemented in genres.controller.spec.ts.

**Comment by samarsrivastav** [comment]
Hey @FrancescObrador !!
I would love to work on this if you would assign me this issue

**Comment by FrancescObrador** [comment]
Hello @samarsrivastav, this issue is open as part of a test I'm doing for a community to form work groups with other juniors. I would be glad to receive your help! Thank You ❤️

**Comment by samarsrivastav** [comment]
hey @FrancescObrador , i can see there are two pages genere.controller.specs and service.specs......

the router in controller.specs is being implemented in controller page 
you want a similar work in the service page

is that correct?

**Comment by FrancescObrador** [comment]
Yes
